### ISSUE TITLE
Error with Export Key

### ISSUE THREAD

**Issue by 4w4k3** [NullArray/Cypher#1]
File: [cyphermain.py](https://github.com/NullArray/Cypher/blob/master/cyphermain.py)
On Line 176:
`	exKey = RSA.exportKey('PEM')`
Change to:
`	exKey = key.exportKey('PEM')`

And move files from **[bootlocker](https://github.com/NullArray/Cypher/tree/master/bootlocker)** to main directory(_[Cypher](https://github.com/NullArray/Cypher)_).
To works fine, you need change its.

**Comment by NullArray** [comment]
Thank you for the issue, i implemented the fix you suggested. Also, when you clone the repo you can move boot.bin to the main directory yourself. So i see no issue with that. The reason it has it's own directory is purely for organisational purposes.
